export PATH="/home/local/ANT/berlandk/perl5/bin${PATH:+:${PATH}}"
export PERL5LIB="/home/local/ANT/berlandk/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"
export PERL_LOCAL_LIB_ROOT="/home/local/ANT/berlandk/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"
export PERL_MB_OPT="--install_base \"/home/local/ANT/berlandk/perl5\""
export PERL_MM_OPT="INSTALL_BASE=/home/local/ANT/berlandk/perl5"
